var summary = {
    "Global": {
        "NewConfirmed": 92968,
        "TotalConfirmed": 4710551,
        "NewDeaths": 4236,
        "TotalDeaths": 317564,
        "NewRecovered": 56138,
        "TotalRecovered": 1692554
    },
    "Countries": [{
            "Country": "Afghanistan",
            "CountryCode": "AF",
            "Slug": "afghanistan",
            "NewConfirmed": 349,
            "TotalConfirmed": 6402,
            "NewDeaths": 15,
            "TotalDeaths": 168,
            "NewRecovered": 0,
            "TotalRecovered": 745,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Albania",
            "CountryCode": "AL",
            "Slug": "albania",
            "NewConfirmed": 17,
            "TotalConfirmed": 933,
            "NewDeaths": 0,
            "TotalDeaths": 31,
            "NewRecovered": 9,
            "TotalRecovered": 714,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Algeria",
            "CountryCode": "DZ",
            "Slug": "algeria",
            "NewConfirmed": 192,
            "TotalConfirmed": 6821,
            "NewDeaths": 6,
            "TotalDeaths": 542,
            "NewRecovered": 138,
            "TotalRecovered": 3409,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Andorra",
            "CountryCode": "AD",
            "Slug": "andorra",
            "NewConfirmed": 0,
            "TotalConfirmed": 761,
            "NewDeaths": 2,
            "TotalDeaths": 51,
            "NewRecovered": 11,
            "TotalRecovered": 615,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Angola",
            "CountryCode": "AO",
            "Slug": "angola",
            "NewConfirmed": 0,
            "TotalConfirmed": 48,
            "NewDeaths": 0,
            "TotalDeaths": 2,
            "NewRecovered": 0,
            "TotalRecovered": 17,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Antigua and Barbuda",
            "CountryCode": "AG",
            "Slug": "antigua-and-barbuda",
            "NewConfirmed": 0,
            "TotalConfirmed": 25,
            "NewDeaths": 0,
            "TotalDeaths": 3,
            "NewRecovered": 0,
            "TotalRecovered": 19,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Argentina",
            "CountryCode": "AR",
            "Slug": "argentina",
            "NewConfirmed": 326,
            "TotalConfirmed": 7805,
            "NewDeaths": 7,
            "TotalDeaths": 363,
            "NewRecovered": 37,
            "TotalRecovered": 2534,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Armenia",
            "CountryCode": "AM",
            "Slug": "armenia",
            "NewConfirmed": 239,
            "TotalConfirmed": 4283,
            "NewDeaths": 3,
            "TotalDeaths": 55,
            "NewRecovered": 125,
            "TotalRecovered": 1791,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Australia",
            "CountryCode": "AU",
            "Slug": "australia",
            "NewConfirmed": 9,
            "TotalConfirmed": 7044,
            "NewDeaths": 0,
            "TotalDeaths": 98,
            "NewRecovered": 5,
            "TotalRecovered": 6364,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Austria",
            "CountryCode": "AT",
            "Slug": "austria",
            "NewConfirmed": 92,
            "TotalConfirmed": 16201,
            "NewDeaths": 1,
            "TotalDeaths": 629,
            "NewRecovered": 53,
            "TotalRecovered": 14524,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Azerbaijan",
            "CountryCode": "AZ",
            "Slug": "azerbaijan",
            "NewConfirmed": 158,
            "TotalConfirmed": 3138,
            "NewDeaths": 0,
            "TotalDeaths": 36,
            "NewRecovered": 58,
            "TotalRecovered": 1944,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Bahamas",
            "CountryCode": "BS",
            "Slug": "bahamas",
            "NewConfirmed": 0,
            "TotalConfirmed": 96,
            "NewDeaths": 0,
            "TotalDeaths": 11,
            "NewRecovered": 1,
            "TotalRecovered": 42,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Bahrain",
            "CountryCode": "BH",
            "Slug": "bahrain",
            "NewConfirmed": 164,
            "TotalConfirmed": 6747,
            "NewDeaths": 0,
            "TotalDeaths": 12,
            "NewRecovered": 122,
            "TotalRecovered": 2762,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Bangladesh",
            "CountryCode": "BD",
            "Slug": "bangladesh",
            "NewConfirmed": 930,
            "TotalConfirmed": 20995,
            "NewDeaths": 16,
            "TotalDeaths": 314,
            "NewRecovered": 235,
            "TotalRecovered": 4117,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Barbados",
            "CountryCode": "BB",
            "Slug": "barbados",
            "NewConfirmed": 1,
            "TotalConfirmed": 86,
            "NewDeaths": 0,
            "TotalDeaths": 7,
            "NewRecovered": 2,
            "TotalRecovered": 67,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Belarus",
            "CountryCode": "BY",
            "Slug": "belarus",
            "NewConfirmed": 951,
            "TotalConfirmed": 28681,
            "NewDeaths": 4,
            "TotalDeaths": 160,
            "NewRecovered": 691,
            "TotalRecovered": 9498,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Belgium",
            "CountryCode": "BE",
            "Slug": "belgium",
            "NewConfirmed": 345,
            "TotalConfirmed": 54989,
            "NewDeaths": 46,
            "TotalDeaths": 9005,
            "NewRecovered": 159,
            "TotalRecovered": 14460,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Belize",
            "CountryCode": "BZ",
            "Slug": "belize",
            "NewConfirmed": 0,
            "TotalConfirmed": 18,
            "NewDeaths": 0,
            "TotalDeaths": 2,
            "NewRecovered": 0,
            "TotalRecovered": 16,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Benin",
            "CountryCode": "BJ",
            "Slug": "benin",
            "NewConfirmed": 0,
            "TotalConfirmed": 339,
            "NewDeaths": 0,
            "TotalDeaths": 2,
            "NewRecovered": 0,
            "TotalRecovered": 83,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Bhutan",
            "CountryCode": "BT",
            "Slug": "bhutan",
            "NewConfirmed": 0,
            "TotalConfirmed": 21,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 5,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Bolivia",
            "CountryCode": "BO",
            "Slug": "bolivia",
            "NewConfirmed": 249,
            "TotalConfirmed": 3826,
            "NewDeaths": 1,
            "TotalDeaths": 165,
            "NewRecovered": 39,
            "TotalRecovered": 473,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Bosnia and Herzegovina",
            "CountryCode": "BA",
            "Slug": "bosnia-and-herzegovina",
            "NewConfirmed": 31,
            "TotalConfirmed": 2267,
            "NewDeaths": 1,
            "TotalDeaths": 129,
            "NewRecovered": 19,
            "TotalRecovered": 1355,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Botswana",
            "CountryCode": "BW",
            "Slug": "botswana",
            "NewConfirmed": 0,
            "TotalConfirmed": 24,
            "NewDeaths": 0,
            "TotalDeaths": 1,
            "NewRecovered": 0,
            "TotalRecovered": 17,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Brazil",
            "CountryCode": "BR",
            "Slug": "brazil",
            "NewConfirmed": 13220,
            "TotalConfirmed": 233511,
            "NewDeaths": 700,
            "TotalDeaths": 15662,
            "NewRecovered": 4702,
            "TotalRecovered": 89672,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Brunei Darussalam",
            "CountryCode": "BN",
            "Slug": "brunei",
            "NewConfirmed": 0,
            "TotalConfirmed": 141,
            "NewDeaths": 0,
            "TotalDeaths": 1,
            "NewRecovered": 1,
            "TotalRecovered": 136,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Bulgaria",
            "CountryCode": "BG",
            "Slug": "bulgaria",
            "NewConfirmed": 37,
            "TotalConfirmed": 2175,
            "NewDeaths": 3,
            "TotalDeaths": 105,
            "NewRecovered": 28,
            "TotalRecovered": 573,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Burkina Faso",
            "CountryCode": "BF",
            "Slug": "burkina-faso",
            "NewConfirmed": 2,
            "TotalConfirmed": 782,
            "NewDeaths": 0,
            "TotalDeaths": 51,
            "NewRecovered": 9,
            "TotalRecovered": 604,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Burundi",
            "CountryCode": "BI",
            "Slug": "burundi",
            "NewConfirmed": 0,
            "TotalConfirmed": 15,
            "NewDeaths": 0,
            "TotalDeaths": 1,
            "NewRecovered": 0,
            "TotalRecovered": 7,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Cambodia",
            "CountryCode": "KH",
            "Slug": "cambodia",
            "NewConfirmed": 0,
            "TotalConfirmed": 122,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 122,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Cameroon",
            "CountryCode": "CM",
            "Slug": "cameroon",
            "NewConfirmed": 0,
            "TotalConfirmed": 3105,
            "NewDeaths": 0,
            "TotalDeaths": 140,
            "NewRecovered": 0,
            "TotalRecovered": 1567,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Canada",
            "CountryCode": "CA",
            "Slug": "canada",
            "NewConfirmed": 2494,
            "TotalConfirmed": 154410,
            "NewDeaths": 242,
            "TotalDeaths": 11598,
            "NewRecovered": 924,
            "TotalRecovered": 37832,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Cape Verde",
            "CountryCode": "CV",
            "Slug": "cape-verde",
            "NewConfirmed": 2,
            "TotalConfirmed": 328,
            "NewDeaths": 1,
            "TotalDeaths": 3,
            "NewRecovered": 17,
            "TotalRecovered": 84,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Central African Republic",
            "CountryCode": "CF",
            "Slug": "central-african-republic",
            "NewConfirmed": 26,
            "TotalConfirmed": 327,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 13,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Chad",
            "CountryCode": "TD",
            "Slug": "chad",
            "NewConfirmed": 46,
            "TotalConfirmed": 474,
            "NewDeaths": 2,
            "TotalDeaths": 50,
            "NewRecovered": 23,
            "TotalRecovered": 111,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Chile",
            "CountryCode": "CL",
            "Slug": "chile",
            "NewConfirmed": 1886,
            "TotalConfirmed": 41428,
            "NewDeaths": 27,
            "TotalDeaths": 421,
            "NewRecovered": 1400,
            "TotalRecovered": 18014,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "China",
            "CountryCode": "CN",
            "Slug": "china",
            "NewConfirmed": 6,
            "TotalConfirmed": 84044,
            "NewDeaths": 1,
            "TotalDeaths": 4638,
            "NewRecovered": 12,
            "TotalRecovered": 79293,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Colombia",
            "CountryCode": "CO",
            "Slug": "colombia",
            "NewConfirmed": 723,
            "TotalConfirmed": 14939,
            "NewDeaths": 16,
            "TotalDeaths": 562,
            "NewRecovered": 127,
            "TotalRecovered": 3587,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Comoros",
            "CountryCode": "KM",
            "Slug": "comoros",
            "NewConfirmed": 0,
            "TotalConfirmed": 11,
            "NewDeaths": 0,
            "TotalDeaths": 1,
            "NewRecovered": 0,
            "TotalRecovered": 3,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Congo (Brazzaville)",
            "CountryCode": "CG",
            "Slug": "congo-brazzaville",
            "NewConfirmed": 0,
            "TotalConfirmed": 391,
            "NewDeaths": 0,
            "TotalDeaths": 15,
            "NewRecovered": 0,
            "TotalRecovered": 87,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Congo (Kinshasa)",
            "CountryCode": "CD",
            "Slug": "congo-kinshasa",
            "NewConfirmed": 157,
            "TotalConfirmed": 1455,
            "NewDeaths": 11,
            "TotalDeaths": 61,
            "NewRecovered": 58,
            "TotalRecovered": 270,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Costa Rica",
            "CountryCode": "CR",
            "Slug": "costa-rica",
            "NewConfirmed": 10,
            "TotalConfirmed": 853,
            "NewDeaths": 1,
            "TotalDeaths": 10,
            "NewRecovered": 9,
            "TotalRecovered": 551,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Croatia",
            "CountryCode": "HR",
            "Slug": "croatia",
            "NewConfirmed": 2,
            "TotalConfirmed": 2224,
            "NewDeaths": 0,
            "TotalDeaths": 95,
            "NewRecovered": 44,
            "TotalRecovered": 1913,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Cuba",
            "CountryCode": "CU",
            "Slug": "cuba",
            "NewConfirmed": 22,
            "TotalConfirmed": 1862,
            "NewDeaths": 0,
            "TotalDeaths": 79,
            "NewRecovered": 35,
            "TotalRecovered": 1460,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Cyprus",
            "CountryCode": "CY",
            "Slug": "cyprus",
            "NewConfirmed": 4,
            "TotalConfirmed": 914,
            "NewDeaths": 0,
            "TotalDeaths": 17,
            "NewRecovered": 34,
            "TotalRecovered": 515,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Czech Republic",
            "CountryCode": "CZ",
            "Slug": "czech-republic",
            "NewConfirmed": 49,
            "TotalConfirmed": 8455,
            "NewDeaths": 1,
            "TotalDeaths": 296,
            "NewRecovered": 41,
            "TotalRecovered": 5422,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Côte d'Ivoire",
            "CountryCode": "CI",
            "Slug": "cote-divoire",
            "NewConfirmed": 44,
            "TotalConfirmed": 2061,
            "NewDeaths": 1,
            "TotalDeaths": 25,
            "NewRecovered": 45,
            "TotalRecovered": 987,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Denmark",
            "CountryCode": "DK",
            "Slug": "denmark",
            "NewConfirmed": 67,
            "TotalConfirmed": 11056,
            "NewDeaths": 6,
            "TotalDeaths": 543,
            "NewRecovered": 148,
            "TotalRecovered": 9305,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Djibouti",
            "CountryCode": "DJ",
            "Slug": "djibouti",
            "NewConfirmed": 22,
            "TotalConfirmed": 1331,
            "NewDeaths": 0,
            "TotalDeaths": 4,
            "NewRecovered": 15,
            "TotalRecovered": 950,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Dominica",
            "CountryCode": "DM",
            "Slug": "dominica",
            "NewConfirmed": 0,
            "TotalConfirmed": 16,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 15,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Dominican Republic",
            "CountryCode": "DO",
            "Slug": "dominican-republic",
            "NewConfirmed": 371,
            "TotalConfirmed": 12110,
            "NewDeaths": 4,
            "TotalDeaths": 428,
            "NewRecovered": 169,
            "TotalRecovered": 3726,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Ecuador",
            "CountryCode": "EC",
            "Slug": "ecuador",
            "NewConfirmed": 1296,
            "TotalConfirmed": 32763,
            "NewDeaths": 94,
            "TotalDeaths": 2688,
            "NewRecovered": 0,
            "TotalRecovered": 3433,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Egypt",
            "CountryCode": "EG",
            "Slug": "egypt",
            "NewConfirmed": 491,
            "TotalConfirmed": 11719,
            "NewDeaths": 20,
            "TotalDeaths": 612,
            "NewRecovered": 151,
            "TotalRecovered": 2950,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "El Salvador",
            "CountryCode": "SV",
            "Slug": "el-salvador",
            "NewConfirmed": 55,
            "TotalConfirmed": 1265,
            "NewDeaths": 1,
            "TotalDeaths": 26,
            "NewRecovered": 24,
            "TotalRecovered": 441,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Equatorial Guinea",
            "CountryCode": "GQ",
            "Slug": "equatorial-guinea",
            "NewConfirmed": 0,
            "TotalConfirmed": 594,
            "NewDeaths": 0,
            "TotalDeaths": 7,
            "NewRecovered": 0,
            "TotalRecovered": 22,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Eritrea",
            "CountryCode": "ER",
            "Slug": "eritrea",
            "NewConfirmed": 0,
            "TotalConfirmed": 39,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 39,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Estonia",
            "CountryCode": "EE",
            "Slug": "estonia",
            "NewConfirmed": 4,
            "TotalConfirmed": 1770,
            "NewDeaths": 0,
            "TotalDeaths": 63,
            "NewRecovered": 11,
            "TotalRecovered": 934,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Ethiopia",
            "CountryCode": "ET",
            "Slug": "ethiopia",
            "NewConfirmed": 19,
            "TotalConfirmed": 306,
            "NewDeaths": 0,
            "TotalDeaths": 5,
            "NewRecovered": 1,
            "TotalRecovered": 113,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Fiji",
            "CountryCode": "FJ",
            "Slug": "fiji",
            "NewConfirmed": 0,
            "TotalConfirmed": 18,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 15,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Finland",
            "CountryCode": "FI",
            "Slug": "finland",
            "NewConfirmed": 58,
            "TotalConfirmed": 6286,
            "NewDeaths": 4,
            "TotalDeaths": 297,
            "NewRecovered": 0,
            "TotalRecovered": 5000,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "France",
            "CountryCode": "FR",
            "Slug": "france",
            "NewConfirmed": 0,
            "TotalConfirmed": 179630,
            "NewDeaths": 0,
            "TotalDeaths": 27532,
            "NewRecovered": 0,
            "TotalRecovered": 60562,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Gabon",
            "CountryCode": "GA",
            "Slug": "gabon",
            "NewConfirmed": 111,
            "TotalConfirmed": 1320,
            "NewDeaths": 1,
            "TotalDeaths": 11,
            "NewRecovered": 25,
            "TotalRecovered": 244,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Gambia",
            "CountryCode": "GM",
            "Slug": "gambia",
            "NewConfirmed": 0,
            "TotalConfirmed": 23,
            "NewDeaths": 0,
            "TotalDeaths": 1,
            "NewRecovered": 2,
            "TotalRecovered": 12,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Georgia",
            "CountryCode": "GE",
            "Slug": "georgia",
            "NewConfirmed": 12,
            "TotalConfirmed": 683,
            "NewDeaths": 0,
            "TotalDeaths": 12,
            "NewRecovered": 26,
            "TotalRecovered": 419,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Germany",
            "CountryCode": "DE",
            "Slug": "germany",
            "NewConfirmed": 519,
            "TotalConfirmed": 175752,
            "NewDeaths": 41,
            "TotalDeaths": 7938,
            "NewRecovered": 1003,
            "TotalRecovered": 152600,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Ghana",
            "CountryCode": "GH",
            "Slug": "ghana",
            "NewConfirmed": 97,
            "TotalConfirmed": 5735,
            "NewDeaths": 1,
            "TotalDeaths": 29,
            "NewRecovered": 294,
            "TotalRecovered": 1754,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Greece",
            "CountryCode": "GR",
            "Slug": "greece",
            "NewConfirmed": 9,
            "TotalConfirmed": 2819,
            "NewDeaths": 2,
            "TotalDeaths": 162,
            "NewRecovered": 0,
            "TotalRecovered": 1374,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Grenada",
            "CountryCode": "GD",
            "Slug": "grenada",
            "NewConfirmed": 0,
            "TotalConfirmed": 22,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 14,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Guatemala",
            "CountryCode": "GT",
            "Slug": "guatemala",
            "NewConfirmed": 120,
            "TotalConfirmed": 1763,
            "NewDeaths": 3,
            "TotalDeaths": 33,
            "NewRecovered": 3,
            "TotalRecovered": 138,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Guinea",
            "CountryCode": "GN",
            "Slug": "guinea",
            "NewConfirmed": 185,
            "TotalConfirmed": 2658,
            "NewDeaths": 1,
            "TotalDeaths": 16,
            "NewRecovered": 238,
            "TotalRecovered": 1133,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Guinea-Bissau",
            "CountryCode": "GW",
            "Slug": "guinea-bissau",
            "NewConfirmed": 56,
            "TotalConfirmed": 969,
            "NewDeaths": 1,
            "TotalDeaths": 4,
            "NewRecovered": 0,
            "TotalRecovered": 26,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Guyana",
            "CountryCode": "GY",
            "Slug": "guyana",
            "NewConfirmed": 1,
            "TotalConfirmed": 117,
            "NewDeaths": 0,
            "TotalDeaths": 10,
            "NewRecovered": 0,
            "TotalRecovered": 43,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Haiti",
            "CountryCode": "HT",
            "Slug": "haiti",
            "NewConfirmed": 48,
            "TotalConfirmed": 358,
            "NewDeaths": 0,
            "TotalDeaths": 20,
            "NewRecovered": 0,
            "TotalRecovered": 29,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Holy See (Vatican City State)",
            "CountryCode": "VA",
            "Slug": "holy-see-vatican-city-state",
            "NewConfirmed": 0,
            "TotalConfirmed": 12,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 2,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Honduras",
            "CountryCode": "HN",
            "Slug": "honduras",
            "NewConfirmed": 105,
            "TotalConfirmed": 2565,
            "NewDeaths": 4,
            "TotalDeaths": 138,
            "NewRecovered": 14,
            "TotalRecovered": 278,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Hungary",
            "CountryCode": "HU",
            "Slug": "hungary",
            "NewConfirmed": 56,
            "TotalConfirmed": 3473,
            "NewDeaths": 6,
            "TotalDeaths": 448,
            "NewRecovered": 84,
            "TotalRecovered": 1371,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Iceland",
            "CountryCode": "IS",
            "Slug": "iceland",
            "NewConfirmed": 0,
            "TotalConfirmed": 1802,
            "NewDeaths": 0,
            "TotalDeaths": 10,
            "NewRecovered": 4,
            "TotalRecovered": 1786,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "India",
            "CountryCode": "IN",
            "Slug": "india",
            "NewConfirmed": 4864,
            "TotalConfirmed": 90648,
            "NewDeaths": 118,
            "TotalDeaths": 2871,
            "NewRecovered": 3966,
            "TotalRecovered": 34224,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Indonesia",
            "CountryCode": "ID",
            "Slug": "indonesia",
            "NewConfirmed": 529,
            "TotalConfirmed": 17025,
            "NewDeaths": 13,
            "TotalDeaths": 1089,
            "NewRecovered": 108,
            "TotalRecovered": 3911,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Iran, Islamic Republic of",
            "CountryCode": "IR",
            "Slug": "iran",
            "NewConfirmed": 1757,
            "TotalConfirmed": 118392,
            "NewDeaths": 35,
            "TotalDeaths": 6937,
            "NewRecovered": 1311,
            "TotalRecovered": 93147,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Iraq",
            "CountryCode": "IQ",
            "Slug": "iraq",
            "NewConfirmed": 67,
            "TotalConfirmed": 3260,
            "NewDeaths": 4,
            "TotalDeaths": 121,
            "NewRecovered": 37,
            "TotalRecovered": 2126,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Ireland",
            "CountryCode": "IE",
            "Slug": "ireland",
            "NewConfirmed": 92,
            "TotalConfirmed": 24048,
            "NewDeaths": 15,
            "TotalDeaths": 1533,
            "NewRecovered": 0,
            "TotalRecovered": 19470,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Israel",
            "CountryCode": "IL",
            "Slug": "israel",
            "NewConfirmed": 19,
            "TotalConfirmed": 16608,
            "NewDeaths": 2,
            "TotalDeaths": 268,
            "NewRecovered": 268,
            "TotalRecovered": 12855,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Italy",
            "CountryCode": "IT",
            "Slug": "italy",
            "NewConfirmed": 875,
            "TotalConfirmed": 224760,
            "NewDeaths": 153,
            "TotalDeaths": 31763,
            "NewRecovered": 2605,
            "TotalRecovered": 122810,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Jamaica",
            "CountryCode": "JM",
            "Slug": "jamaica",
            "NewConfirmed": 6,
            "TotalConfirmed": 517,
            "NewDeaths": 0,
            "TotalDeaths": 9,
            "NewRecovered": 0,
            "TotalRecovered": 121,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Japan",
            "CountryCode": "JP",
            "Slug": "japan",
            "NewConfirmed": 34,
            "TotalConfirmed": 16237,
            "NewDeaths": 12,
            "TotalDeaths": 725,
            "NewRecovered": 0,
            "TotalRecovered": 10338,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Jordan",
            "CountryCode": "JO",
            "Slug": "jordan",
            "NewConfirmed": 11,
            "TotalConfirmed": 607,
            "NewDeaths": 0,
            "TotalDeaths": 9,
            "NewRecovered": 3,
            "TotalRecovered": 404,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Kazakhstan",
            "CountryCode": "KZ",
            "Slug": "kazakhstan",
            "NewConfirmed": 161,
            "TotalConfirmed": 5850,
            "NewDeaths": 0,
            "TotalDeaths": 34,
            "NewRecovered": 273,
            "TotalRecovered": 2980,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Kenya",
            "CountryCode": "KE",
            "Slug": "kenya",
            "NewConfirmed": 49,
            "TotalConfirmed": 830,
            "NewDeaths": 5,
            "TotalDeaths": 50,
            "NewRecovered": 17,
            "TotalRecovered": 301,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Korea (South)",
            "CountryCode": "KR",
            "Slug": "korea-south",
            "NewConfirmed": 13,
            "TotalConfirmed": 11050,
            "NewDeaths": 0,
            "TotalDeaths": 262,
            "NewRecovered": 37,
            "TotalRecovered": 9888,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Kuwait",
            "CountryCode": "KW",
            "Slug": "kuwait",
            "NewConfirmed": 942,
            "TotalConfirmed": 13802,
            "NewDeaths": 11,
            "TotalDeaths": 107,
            "NewRecovered": 203,
            "TotalRecovered": 3843,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Kyrgyzstan",
            "CountryCode": "KG",
            "Slug": "kyrgyzstan",
            "NewConfirmed": 6,
            "TotalConfirmed": 1117,
            "NewDeaths": 0,
            "TotalDeaths": 14,
            "NewRecovered": 38,
            "TotalRecovered": 783,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Lao PDR",
            "CountryCode": "LA",
            "Slug": "lao-pdr",
            "NewConfirmed": 0,
            "TotalConfirmed": 19,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 14,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Latvia",
            "CountryCode": "LV",
            "Slug": "latvia",
            "NewConfirmed": 27,
            "TotalConfirmed": 997,
            "NewDeaths": 0,
            "TotalDeaths": 19,
            "NewRecovered": 0,
            "TotalRecovered": 662,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Lebanon",
            "CountryCode": "LB",
            "Slug": "lebanon",
            "NewConfirmed": 11,
            "TotalConfirmed": 902,
            "NewDeaths": 0,
            "TotalDeaths": 26,
            "NewRecovered": 1,
            "TotalRecovered": 247,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Lesotho",
            "CountryCode": "LS",
            "Slug": "lesotho",
            "NewConfirmed": 0,
            "TotalConfirmed": 1,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Liberia",
            "CountryCode": "LR",
            "Slug": "liberia",
            "NewConfirmed": 4,
            "TotalConfirmed": 223,
            "NewDeaths": 0,
            "TotalDeaths": 20,
            "NewRecovered": 8,
            "TotalRecovered": 116,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Libya",
            "CountryCode": "LY",
            "Slug": "libya",
            "NewConfirmed": 1,
            "TotalConfirmed": 65,
            "NewDeaths": 0,
            "TotalDeaths": 3,
            "NewRecovered": 0,
            "TotalRecovered": 28,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Liechtenstein",
            "CountryCode": "LI",
            "Slug": "liechtenstein",
            "NewConfirmed": 0,
            "TotalConfirmed": 82,
            "NewDeaths": 0,
            "TotalDeaths": 1,
            "NewRecovered": 0,
            "TotalRecovered": 55,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Lithuania",
            "CountryCode": "LT",
            "Slug": "lithuania",
            "NewConfirmed": 11,
            "TotalConfirmed": 1534,
            "NewDeaths": 1,
            "TotalDeaths": 55,
            "NewRecovered": 23,
            "TotalRecovered": 988,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Luxembourg",
            "CountryCode": "LU",
            "Slug": "luxembourg",
            "NewConfirmed": 7,
            "TotalConfirmed": 3930,
            "NewDeaths": 0,
            "TotalDeaths": 104,
            "NewRecovered": 17,
            "TotalRecovered": 3699,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Macedonia, Republic of",
            "CountryCode": "MK",
            "Slug": "macedonia",
            "NewConfirmed": 22,
            "TotalConfirmed": 1762,
            "NewDeaths": 1,
            "TotalDeaths": 98,
            "NewRecovered": 16,
            "TotalRecovered": 1267,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Madagascar",
            "CountryCode": "MG",
            "Slug": "madagascar",
            "NewConfirmed": 45,
            "TotalConfirmed": 283,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 2,
            "TotalRecovered": 114,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Malawi",
            "CountryCode": "MW",
            "Slug": "malawi",
            "NewConfirmed": 2,
            "TotalConfirmed": 65,
            "NewDeaths": 0,
            "TotalDeaths": 3,
            "NewRecovered": 0,
            "TotalRecovered": 24,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Malaysia",
            "CountryCode": "MY",
            "Slug": "malaysia",
            "NewConfirmed": 17,
            "TotalConfirmed": 6872,
            "NewDeaths": 1,
            "TotalDeaths": 113,
            "NewRecovered": 73,
            "TotalRecovered": 5512,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Maldives",
            "CountryCode": "MV",
            "Slug": "maldives",
            "NewConfirmed": 47,
            "TotalConfirmed": 1078,
            "NewDeaths": 0,
            "TotalDeaths": 4,
            "NewRecovered": 9,
            "TotalRecovered": 58,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Mali",
            "CountryCode": "ML",
            "Slug": "mali",
            "NewConfirmed": 29,
            "TotalConfirmed": 835,
            "NewDeaths": 2,
            "TotalDeaths": 48,
            "NewRecovered": 24,
            "TotalRecovered": 479,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Malta",
            "CountryCode": "MT",
            "Slug": "malta",
            "NewConfirmed": 14,
            "TotalConfirmed": 546,
            "NewDeaths": 0,
            "TotalDeaths": 6,
            "NewRecovered": 0,
            "TotalRecovered": 458,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Mauritania",
            "CountryCode": "MR",
            "Slug": "mauritania",
            "NewConfirmed": 11,
            "TotalConfirmed": 40,
            "NewDeaths": 1,
            "TotalDeaths": 4,
            "NewRecovered": 0,
            "TotalRecovered": 7,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Mauritius",
            "CountryCode": "MU",
            "Slug": "mauritius",
            "NewConfirmed": 0,
            "TotalConfirmed": 332,
            "NewDeaths": 0,
            "TotalDeaths": 10,
            "NewRecovered": 0,
            "TotalRecovered": 322,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Mexico",
            "CountryCode": "MX",
            "Slug": "mexico",
            "NewConfirmed": 2112,
            "TotalConfirmed": 47144,
            "NewDeaths": 278,
            "TotalDeaths": 5045,
            "NewRecovered": 1397,
            "TotalRecovered": 31848,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Moldova",
            "CountryCode": "MD",
            "Slug": "moldova",
            "NewConfirmed": 189,
            "TotalConfirmed": 5934,
            "NewDeaths": 5,
            "TotalDeaths": 207,
            "NewRecovered": 116,
            "TotalRecovered": 2344,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Monaco",
            "CountryCode": "MC",
            "Slug": "monaco",
            "NewConfirmed": 0,
            "TotalConfirmed": 96,
            "NewDeaths": 0,
            "TotalDeaths": 4,
            "NewRecovered": 0,
            "TotalRecovered": 87,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Mongolia",
            "CountryCode": "MN",
            "Slug": "mongolia",
            "NewConfirmed": 37,
            "TotalConfirmed": 135,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 20,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Montenegro",
            "CountryCode": "ME",
            "Slug": "montenegro",
            "NewConfirmed": 0,
            "TotalConfirmed": 324,
            "NewDeaths": 0,
            "TotalDeaths": 9,
            "NewRecovered": 0,
            "TotalRecovered": 311,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Morocco",
            "CountryCode": "MA",
            "Slug": "morocco",
            "NewConfirmed": 89,
            "TotalConfirmed": 6741,
            "NewDeaths": 2,
            "TotalDeaths": 192,
            "NewRecovered": 87,
            "TotalRecovered": 3487,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Mozambique",
            "CountryCode": "MZ",
            "Slug": "mozambique",
            "NewConfirmed": 10,
            "TotalConfirmed": 129,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 1,
            "TotalRecovered": 43,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Myanmar",
            "CountryCode": "MM",
            "Slug": "myanmar",
            "NewConfirmed": 0,
            "TotalConfirmed": 182,
            "NewDeaths": 0,
            "TotalDeaths": 6,
            "NewRecovered": 7,
            "TotalRecovered": 96,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Namibia",
            "CountryCode": "NA",
            "Slug": "namibia",
            "NewConfirmed": 0,
            "TotalConfirmed": 16,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 13,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Nepal",
            "CountryCode": "NP",
            "Slug": "nepal",
            "NewConfirmed": 24,
            "TotalConfirmed": 291,
            "NewDeaths": 1,
            "TotalDeaths": 1,
            "NewRecovered": 0,
            "TotalRecovered": 36,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Netherlands",
            "CountryCode": "NL",
            "Slug": "netherlands",
            "NewConfirmed": 190,
            "TotalConfirmed": 44070,
            "NewDeaths": 27,
            "TotalDeaths": 5689,
            "NewRecovered": 8,
            "TotalRecovered": 167,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "New Zealand",
            "CountryCode": "NZ",
            "Slug": "new-zealand",
            "NewConfirmed": 1,
            "TotalConfirmed": 1499,
            "NewDeaths": 0,
            "TotalDeaths": 21,
            "NewRecovered": 5,
            "TotalRecovered": 1433,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Nicaragua",
            "CountryCode": "NI",
            "Slug": "nicaragua",
            "NewConfirmed": 0,
            "TotalConfirmed": 25,
            "NewDeaths": 0,
            "TotalDeaths": 8,
            "NewRecovered": 0,
            "TotalRecovered": 7,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Niger",
            "CountryCode": "NE",
            "Slug": "niger",
            "NewConfirmed": 4,
            "TotalConfirmed": 889,
            "NewDeaths": 0,
            "TotalDeaths": 51,
            "NewRecovered": 5,
            "TotalRecovered": 689,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Nigeria",
            "CountryCode": "NG",
            "Slug": "nigeria",
            "NewConfirmed": 171,
            "TotalConfirmed": 5621,
            "NewDeaths": 5,
            "TotalDeaths": 176,
            "NewRecovered": 152,
            "TotalRecovered": 1472,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Norway",
            "CountryCode": "NO",
            "Slug": "norway",
            "NewConfirmed": 18,
            "TotalConfirmed": 8237,
            "NewDeaths": 0,
            "TotalDeaths": 232,
            "NewRecovered": 0,
            "TotalRecovered": 32,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Oman",
            "CountryCode": "OM",
            "Slug": "oman",
            "NewConfirmed": 404,
            "TotalConfirmed": 5029,
            "NewDeaths": 1,
            "TotalDeaths": 21,
            "NewRecovered": 86,
            "TotalRecovered": 1436,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Pakistan",
            "CountryCode": "PK",
            "Slug": "pakistan",
            "NewConfirmed": 0,
            "TotalConfirmed": 38799,
            "NewDeaths": 0,
            "TotalDeaths": 834,
            "NewRecovered": 0,
            "TotalRecovered": 10880,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Palestinian Territory",
            "CountryCode": "PS",
            "Slug": "palestine",
            "NewConfirmed": 1,
            "TotalConfirmed": 376,
            "NewDeaths": 0,
            "TotalDeaths": 2,
            "NewRecovered": 14,
            "TotalRecovered": 329,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Panama",
            "CountryCode": "PA",
            "Slug": "panama",
            "NewConfirmed": 181,
            "TotalConfirmed": 9449,
            "NewDeaths": 3,
            "TotalDeaths": 269,
            "NewRecovered": 0,
            "TotalRecovered": 6080,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Papua New Guinea",
            "CountryCode": "PG",
            "Slug": "papua-new-guinea",
            "NewConfirmed": 0,
            "TotalConfirmed": 8,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 8,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Paraguay",
            "CountryCode": "PY",
            "Slug": "paraguay",
            "NewConfirmed": 19,
            "TotalConfirmed": 778,
            "NewDeaths": 0,
            "TotalDeaths": 11,
            "NewRecovered": 5,
            "TotalRecovered": 198,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Peru",
            "CountryCode": "PE",
            "Slug": "peru",
            "NewConfirmed": 4046,
            "TotalConfirmed": 88541,
            "NewDeaths": 131,
            "TotalDeaths": 2523,
            "NewRecovered": 1125,
            "TotalRecovered": 28272,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Philippines",
            "CountryCode": "PH",
            "Slug": "philippines",
            "NewConfirmed": 214,
            "TotalConfirmed": 12305,
            "NewDeaths": 11,
            "TotalDeaths": 817,
            "NewRecovered": 101,
            "TotalRecovered": 2561,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Poland",
            "CountryCode": "PL",
            "Slug": "poland",
            "NewConfirmed": 241,
            "TotalConfirmed": 18257,
            "NewDeaths": 8,
            "TotalDeaths": 915,
            "NewRecovered": 257,
            "TotalRecovered": 7175,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Portugal",
            "CountryCode": "PT",
            "Slug": "portugal",
            "NewConfirmed": 227,
            "TotalConfirmed": 28810,
            "NewDeaths": 13,
            "TotalDeaths": 1203,
            "NewRecovered": 494,
            "TotalRecovered": 3822,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Qatar",
            "CountryCode": "QA",
            "Slug": "qatar",
            "NewConfirmed": 1547,
            "TotalConfirmed": 30972,
            "NewDeaths": 1,
            "TotalDeaths": 15,
            "NewRecovered": 242,
            "TotalRecovered": 3788,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Republic of Kosovo",
            "CountryCode": "XK",
            "Slug": "kosovo",
            "NewConfirmed": 0,
            "TotalConfirmed": 944,
            "NewDeaths": 0,
            "TotalDeaths": 29,
            "NewRecovered": 0,
            "TotalRecovered": 690,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Romania",
            "CountryCode": "RO",
            "Slug": "romania",
            "NewConfirmed": 267,
            "TotalConfirmed": 16704,
            "NewDeaths": 24,
            "TotalDeaths": 1094,
            "NewRecovered": 204,
            "TotalRecovered": 9574,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Russian Federation",
            "CountryCode": "RU",
            "Slug": "russia",
            "NewConfirmed": 9200,
            "TotalConfirmed": 272043,
            "NewDeaths": 119,
            "TotalDeaths": 2537,
            "NewRecovered": 4940,
            "TotalRecovered": 63166,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Rwanda",
            "CountryCode": "RW",
            "Slug": "rwanda",
            "NewConfirmed": 2,
            "TotalConfirmed": 289,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 1,
            "TotalRecovered": 178,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Saint Kitts and Nevis",
            "CountryCode": "KN",
            "Slug": "saint-kitts-and-nevis",
            "NewConfirmed": 0,
            "TotalConfirmed": 15,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 14,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Saint Lucia",
            "CountryCode": "LC",
            "Slug": "saint-lucia",
            "NewConfirmed": 0,
            "TotalConfirmed": 18,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 18,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Saint Vincent and Grenadines",
            "CountryCode": "VC",
            "Slug": "saint-vincent-and-the-grenadines",
            "NewConfirmed": 0,
            "TotalConfirmed": 17,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 14,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "San Marino",
            "CountryCode": "SM",
            "Slug": "san-marino",
            "NewConfirmed": 1,
            "TotalConfirmed": 653,
            "NewDeaths": 0,
            "TotalDeaths": 41,
            "NewRecovered": 9,
            "TotalRecovered": 198,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Sao Tome and Principe",
            "CountryCode": "ST",
            "Slug": "sao-tome-and-principe",
            "NewConfirmed": 0,
            "TotalConfirmed": 235,
            "NewDeaths": 0,
            "TotalDeaths": 7,
            "NewRecovered": 0,
            "TotalRecovered": 4,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Saudi Arabia",
            "CountryCode": "SA",
            "Slug": "saudi-arabia",
            "NewConfirmed": 2840,
            "TotalConfirmed": 52016,
            "NewDeaths": 10,
            "TotalDeaths": 302,
            "NewRecovered": 1797,
            "TotalRecovered": 23666,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Senegal",
            "CountryCode": "SN",
            "Slug": "senegal",
            "NewConfirmed": 119,
            "TotalConfirmed": 2429,
            "NewDeaths": 0,
            "TotalDeaths": 25,
            "NewRecovered": 59,
            "TotalRecovered": 949,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Serbia",
            "CountryCode": "RS",
            "Slug": "serbia",
            "NewConfirmed": 58,
            "TotalConfirmed": 10496,
            "NewDeaths": 3,
            "TotalDeaths": 228,
            "NewRecovered": 178,
            "TotalRecovered": 4479,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Seychelles",
            "CountryCode": "SC",
            "Slug": "seychelles",
            "NewConfirmed": 0,
            "TotalConfirmed": 11,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 10,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Sierra Leone",
            "CountryCode": "SL",
            "Slug": "sierra-leone",
            "NewConfirmed": 15,
            "TotalConfirmed": 462,
            "NewDeaths": 2,
            "TotalDeaths": 29,
            "NewRecovered": 9,
            "TotalRecovered": 106,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Singapore",
            "CountryCode": "SG",
            "Slug": "singapore",
            "NewConfirmed": 465,
            "TotalConfirmed": 27356,
            "NewDeaths": 1,
            "TotalDeaths": 22,
            "NewRecovered": 1094,
            "TotalRecovered": 8342,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Slovakia",
            "CountryCode": "SK",
            "Slug": "slovakia",
            "NewConfirmed": 13,
            "TotalConfirmed": 1493,
            "NewDeaths": 1,
            "TotalDeaths": 28,
            "NewRecovered": 20,
            "TotalRecovered": 1151,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Slovenia",
            "CountryCode": "SI",
            "Slug": "slovenia",
            "NewConfirmed": 0,
            "TotalConfirmed": 1465,
            "NewDeaths": 0,
            "TotalDeaths": 103,
            "NewRecovered": 2,
            "TotalRecovered": 272,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Somalia",
            "CountryCode": "SO",
            "Slug": "somalia",
            "NewConfirmed": 73,
            "TotalConfirmed": 1357,
            "NewDeaths": 2,
            "TotalDeaths": 55,
            "NewRecovered": 13,
            "TotalRecovered": 148,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "South Africa",
            "CountryCode": "ZA",
            "Slug": "south-africa",
            "NewConfirmed": 831,
            "TotalConfirmed": 14355,
            "NewDeaths": 14,
            "TotalDeaths": 261,
            "NewRecovered": 395,
            "TotalRecovered": 6478,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "South Sudan",
            "CountryCode": "SS",
            "Slug": "south-sudan",
            "NewConfirmed": 0,
            "TotalConfirmed": 236,
            "NewDeaths": 0,
            "TotalDeaths": 4,
            "NewRecovered": 0,
            "TotalRecovered": 4,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Spain",
            "CountryCode": "ES",
            "Slug": "spain",
            "NewConfirmed": 515,
            "TotalConfirmed": 230698,
            "NewDeaths": 104,
            "TotalDeaths": 27563,
            "NewRecovered": 1663,
            "TotalRecovered": 146446,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Sri Lanka",
            "CountryCode": "LK",
            "Slug": "sri-lanka",
            "NewConfirmed": 25,
            "TotalConfirmed": 960,
            "NewDeaths": 0,
            "TotalDeaths": 9,
            "NewRecovered": 43,
            "TotalRecovered": 520,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Sudan",
            "CountryCode": "SD",
            "Slug": "sudan",
            "NewConfirmed": 325,
            "TotalConfirmed": 2289,
            "NewDeaths": 6,
            "TotalDeaths": 97,
            "NewRecovered": 17,
            "TotalRecovered": 222,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Suriname",
            "CountryCode": "SR",
            "Slug": "suriname",
            "NewConfirmed": 0,
            "TotalConfirmed": 10,
            "NewDeaths": 0,
            "TotalDeaths": 1,
            "NewRecovered": 0,
            "TotalRecovered": 9,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Swaziland",
            "CountryCode": "SZ",
            "Slug": "swaziland",
            "NewConfirmed": 12,
            "TotalConfirmed": 202,
            "NewDeaths": 0,
            "TotalDeaths": 2,
            "NewRecovered": 6,
            "TotalRecovered": 72,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Sweden",
            "CountryCode": "SE",
            "Slug": "sweden",
            "NewConfirmed": 470,
            "TotalConfirmed": 29677,
            "NewDeaths": 28,
            "TotalDeaths": 3674,
            "NewRecovered": 0,
            "TotalRecovered": 4971,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Switzerland",
            "CountryCode": "CH",
            "Slug": "switzerland",
            "NewConfirmed": 58,
            "TotalConfirmed": 30572,
            "NewDeaths": 1,
            "TotalDeaths": 1879,
            "NewRecovered": 300,
            "TotalRecovered": 27400,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Syrian Arab Republic (Syria)",
            "CountryCode": "SY",
            "Slug": "syria",
            "NewConfirmed": 1,
            "TotalConfirmed": 51,
            "NewDeaths": 0,
            "TotalDeaths": 3,
            "NewRecovered": 0,
            "TotalRecovered": 36,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Taiwan, Republic of China",
            "CountryCode": "TW",
            "Slug": "taiwan",
            "NewConfirmed": 0,
            "TotalConfirmed": 440,
            "NewDeaths": 0,
            "TotalDeaths": 7,
            "NewRecovered": 2,
            "TotalRecovered": 389,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Tajikistan",
            "CountryCode": "TJ",
            "Slug": "tajikistan",
            "NewConfirmed": 204,
            "TotalConfirmed": 1322,
            "NewDeaths": 3,
            "TotalDeaths": 36,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Tanzania, United Republic of",
            "CountryCode": "TZ",
            "Slug": "tanzania",
            "NewConfirmed": 0,
            "TotalConfirmed": 509,
            "NewDeaths": 0,
            "TotalDeaths": 21,
            "NewRecovered": 0,
            "TotalRecovered": 183,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Thailand",
            "CountryCode": "TH",
            "Slug": "thailand",
            "NewConfirmed": 0,
            "TotalConfirmed": 3025,
            "NewDeaths": 0,
            "TotalDeaths": 56,
            "NewRecovered": 1,
            "TotalRecovered": 2855,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Timor-Leste",
            "CountryCode": "TL",
            "Slug": "timor-leste",
            "NewConfirmed": 0,
            "TotalConfirmed": 24,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 24,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Togo",
            "CountryCode": "TG",
            "Slug": "togo",
            "NewConfirmed": 35,
            "TotalConfirmed": 298,
            "NewDeaths": 0,
            "TotalDeaths": 11,
            "NewRecovered": 3,
            "TotalRecovered": 99,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Trinidad and Tobago",
            "CountryCode": "TT",
            "Slug": "trinidad-and-tobago",
            "NewConfirmed": 0,
            "TotalConfirmed": 116,
            "NewDeaths": 0,
            "TotalDeaths": 8,
            "NewRecovered": 0,
            "TotalRecovered": 107,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Tunisia",
            "CountryCode": "TN",
            "Slug": "tunisia",
            "NewConfirmed": 2,
            "TotalConfirmed": 1037,
            "NewDeaths": 0,
            "TotalDeaths": 45,
            "NewRecovered": 5,
            "TotalRecovered": 807,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Turkey",
            "CountryCode": "TR",
            "Slug": "turkey",
            "NewConfirmed": 1610,
            "TotalConfirmed": 148067,
            "NewDeaths": 41,
            "TotalDeaths": 4096,
            "NewRecovered": 2004,
            "TotalRecovered": 108137,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Uganda",
            "CountryCode": "UG",
            "Slug": "uganda",
            "NewConfirmed": 24,
            "TotalConfirmed": 227,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 63,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Ukraine",
            "CountryCode": "UA",
            "Slug": "ukraine",
            "NewConfirmed": 528,
            "TotalConfirmed": 17858,
            "NewDeaths": 21,
            "TotalDeaths": 497,
            "NewRecovered": 433,
            "TotalRecovered": 4906,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "United Arab Emirates",
            "CountryCode": "AE",
            "Slug": "united-arab-emirates",
            "NewConfirmed": 796,
            "TotalConfirmed": 22627,
            "NewDeaths": 4,
            "TotalDeaths": 214,
            "NewRecovered": 603,
            "TotalRecovered": 7931,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "United Kingdom",
            "CountryCode": "GB",
            "Slug": "united-kingdom",
            "NewConfirmed": 3457,
            "TotalConfirmed": 241461,
            "NewDeaths": 468,
            "TotalDeaths": 34546,
            "NewRecovered": 11,
            "TotalRecovered": 1058,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "United States of America",
            "CountryCode": "US",
            "Slug": "united-states",
            "NewConfirmed": 24996,
            "TotalConfirmed": 1467820,
            "NewDeaths": 1224,
            "TotalDeaths": 88754,
            "NewRecovered": 17629,
            "TotalRecovered": 268376,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Uruguay",
            "CountryCode": "UY",
            "Slug": "uruguay",
            "NewConfirmed": 1,
            "TotalConfirmed": 733,
            "NewDeaths": 0,
            "TotalDeaths": 19,
            "NewRecovered": 5,
            "TotalRecovered": 558,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Uzbekistan",
            "CountryCode": "UZ",
            "Slug": "uzbekistan",
            "NewConfirmed": 52,
            "TotalConfirmed": 2738,
            "NewDeaths": 0,
            "TotalDeaths": 11,
            "NewRecovered": 55,
            "TotalRecovered": 2213,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Venezuela (Bolivarian Republic)",
            "CountryCode": "VE",
            "Slug": "venezuela",
            "NewConfirmed": 45,
            "TotalConfirmed": 504,
            "NewDeaths": 0,
            "TotalDeaths": 10,
            "NewRecovered": 12,
            "TotalRecovered": 241,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Viet Nam",
            "CountryCode": "VN",
            "Slug": "vietnam",
            "NewConfirmed": 4,
            "TotalConfirmed": 318,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 260,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Western Sahara",
            "CountryCode": "EH",
            "Slug": "western-sahara",
            "NewConfirmed": 0,
            "TotalConfirmed": 6,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 6,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Yemen",
            "CountryCode": "YE",
            "Slug": "yemen",
            "NewConfirmed": 16,
            "TotalConfirmed": 122,
            "NewDeaths": 3,
            "TotalDeaths": 18,
            "NewRecovered": 0,
            "TotalRecovered": 1,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Zambia",
            "CountryCode": "ZM",
            "Slug": "zambia",
            "NewConfirmed": 25,
            "TotalConfirmed": 679,
            "NewDeaths": 0,
            "TotalDeaths": 7,
            "NewRecovered": 59,
            "TotalRecovered": 183,
            "Date": "2020-05-17T09:04:08Z"
        },
        {
            "Country": "Zimbabwe",
            "CountryCode": "ZW",
            "Slug": "zimbabwe",
            "NewConfirmed": 0,
            "TotalConfirmed": 42,
            "NewDeaths": 0,
            "TotalDeaths": 4,
            "NewRecovered": 0,
            "TotalRecovered": 13,
            "Date": "2020-05-17T09:04:08Z"
        }
    ],
    "Date": "2020-05-17T09:04:08Z"
}